#Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
logo: "/img/icon.png"

# Aux links for the upper right navigation
aux_links:
  "Download xs":
    - "https://github.com/BredaUniversityGames/xs/releases"
  "Contribute":
    - "https://github.com/BredaUniversityGames/xs"


footer_content: "Made with ‚ù§ at Breda University of Applied Sciences"